const db_query = {
  tbl_user: {
    id: 'INTEGER PRIMARY KEY AUTOINCREMENT',
    name: ' VARCHAR(50)',
    email: ' VARCHAR(50)',
    password: ' VARCHAR(50)',
    confirm: ' VARCHAR(50)',
  },
  tbl_article: {
    id: 'INTEGER PRIMARY KEY AUTOINCREMENT',
    context: 'VARCHAR(150)',
    type: 'VARCHAR(150)',
    headline: 'VARCHAR(150)',
    alternativeHeadline: 'VARCHAR(150)',
    image: 'VARCHAR(150)',
    author: 'VARCHAR(150)',
    award: 'VARCHAR(150)',
    editor: 'VARCHAR(150)',
    genre: 'VARCHAR(150)',
    keywords: 'VARCHAR(150)',
    wordcount: 'VARCHAR(150)',
    url: 'VARCHAR(150)',
    datePublished: 'VARCHAR(150)',
    dateCreated: 'VARCHAR(150)',
    dateModified: 'VARCHAR(150)',
    description: 'VARCHAR(150)',
    articleBody: 'VARCHAR(150)',
  },
  tbl_porto_profile: {
    id: 'INTEGER PRIMARY KEY AUTOINCREMENT',
    name: 'VARCHAR(150)',
    image: 'VARCHAR(150)',
    profesi: 'VARCHAR(150)',
  },
  tbl_experiences: {
    id: 'INTEGER PRIMARY KEY AUTOINCREMENT',
    joinDate: 'VARCHAR(150)',
    endDate: 'VARCHAR(150)',
    compay: 'VARCHAR(150)',
    position: 'VARCHAR(150)',
    jobdesc: 'VARCHAR(150)',
  },
  tbl_skills: {
    id: 'INTEGER PRIMARY KEY AUTOINCREMENT',
    sub: 'VARCHAR(150)',
    persen: 'VARCHAR(150)',
  },
  tbl_educations: {
    id: 'INTEGER PRIMARY KEY AUTOINCREMENT',
    sub: 'VARCHAR(150)',
    startDate: 'VARCHAR(150)',
    endDate: 'VARCHAR(150)',
    level: 'VARCHAR(150)',
    major: 'VARCHAR(150)',
    concentration: 'VARCHAR(150)',
    gpa: 'VARCHAR(150)',
  },
  tbl_contacts: {
    id: 'INTEGER PRIMARY KEY AUTOINCREMENT',
    type: 'VARCHAR(150)',
    sub: 'VARCHAR(150)',
  },
  tbl_regist:{
    id: 'INTEGER PRIMARY KEY AUTOINCREMENT',
    email: 'VARCHAR(150)',
    password: 'VARCHAR(150)',
    confirm: 'VARCHAR(150)',
  }
};
export default db_query;
